name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn install -DskipTests
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        env:
          filePath: example.json
        run: mvn clean test

  native-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.1
        with:
          graalvm-version: "19.3.1"
          java-version: "java11"
      - name: Test
        env:
          filePath: example.json
        run: |
          gu install native-image
          mvn verify -Pnative
